#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.CambioUPC.BL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbCambioUPC")]
	public partial class dbCambioUPCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTarjeta(Tarjeta instance);
    partial void UpdateTarjeta(Tarjeta instance);
    partial void DeleteTarjeta(Tarjeta instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertTipoTransaccion(TipoTransaccion instance);
    partial void UpdateTipoTransaccion(TipoTransaccion instance);
    partial void DeleteTipoTransaccion(TipoTransaccion instance);
    partial void InsertTransaccion(Transaccion instance);
    partial void UpdateTransaccion(Transaccion instance);
    partial void DeleteTransaccion(Transaccion instance);
    #endregion
		
		public dbCambioUPCDataContext() : 
				base(global::UPC.CambioUPC.BL.Properties.Settings.Default.dbCambioUPCConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbCambioUPCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbCambioUPCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbCambioUPCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbCambioUPCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tarjeta> Tarjetas
		{
			get
			{
				return this.GetTable<Tarjeta>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<TipoTransaccion> TipoTransaccions
		{
			get
			{
				return this.GetTable<TipoTransaccion>();
			}
		}
		
		public System.Data.Linq.Table<Transaccion> Transaccions
		{
			get
			{
				return this.GetTable<Transaccion>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tarjeta")]
	public partial class Tarjeta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Descripcion;
		
		private string _NumeroTarjeta;
		
		private int _IdUsuario;
		
		private int _IdUsuarioRegistro;
		
		private System.DateTime _FechaRegistro;
		
		private System.Nullable<int> _IdUsuarioModifico;
		
		private System.Nullable<System.DateTime> _FechaModifico;
		
		private bool _Eliminado;
		
		private EntitySet<Transaccion> _Transaccions;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnNumeroTarjetaChanging(string value);
    partial void OnNumeroTarjetaChanged();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnIdUsuarioRegistroChanging(int value);
    partial void OnIdUsuarioRegistroChanged();
    partial void OnFechaRegistroChanging(System.DateTime value);
    partial void OnFechaRegistroChanged();
    partial void OnIdUsuarioModificoChanging(System.Nullable<int> value);
    partial void OnIdUsuarioModificoChanged();
    partial void OnFechaModificoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaModificoChanged();
    partial void OnEliminadoChanging(bool value);
    partial void OnEliminadoChanged();
    #endregion
		
		public Tarjeta()
		{
			this._Transaccions = new EntitySet<Transaccion>(new Action<Transaccion>(this.attach_Transaccions), new Action<Transaccion>(this.detach_Transaccions));
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroTarjeta", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NumeroTarjeta
		{
			get
			{
				return this._NumeroTarjeta;
			}
			set
			{
				if ((this._NumeroTarjeta != value))
				{
					this.OnNumeroTarjetaChanging(value);
					this.SendPropertyChanging();
					this._NumeroTarjeta = value;
					this.SendPropertyChanged("NumeroTarjeta");
					this.OnNumeroTarjetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioRegistro", DbType="Int NOT NULL")]
		public int IdUsuarioRegistro
		{
			get
			{
				return this._IdUsuarioRegistro;
			}
			set
			{
				if ((this._IdUsuarioRegistro != value))
				{
					this.OnIdUsuarioRegistroChanging(value);
					this.SendPropertyChanging();
					this._IdUsuarioRegistro = value;
					this.SendPropertyChanged("IdUsuarioRegistro");
					this.OnIdUsuarioRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioModifico", DbType="Int")]
		public System.Nullable<int> IdUsuarioModifico
		{
			get
			{
				return this._IdUsuarioModifico;
			}
			set
			{
				if ((this._IdUsuarioModifico != value))
				{
					this.OnIdUsuarioModificoChanging(value);
					this.SendPropertyChanging();
					this._IdUsuarioModifico = value;
					this.SendPropertyChanged("IdUsuarioModifico");
					this.OnIdUsuarioModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifico", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModifico
		{
			get
			{
				return this._FechaModifico;
			}
			set
			{
				if ((this._FechaModifico != value))
				{
					this.OnFechaModificoChanging(value);
					this.SendPropertyChanging();
					this._FechaModifico = value;
					this.SendPropertyChanged("FechaModifico");
					this.OnFechaModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eliminado", DbType="Bit NOT NULL")]
		public bool Eliminado
		{
			get
			{
				return this._Eliminado;
			}
			set
			{
				if ((this._Eliminado != value))
				{
					this.OnEliminadoChanging(value);
					this.SendPropertyChanging();
					this._Eliminado = value;
					this.SendPropertyChanged("Eliminado");
					this.OnEliminadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tarjeta_Transaccion", Storage="_Transaccions", ThisKey="Id", OtherKey="IdTarjeta")]
		public EntitySet<Transaccion> Transaccions
		{
			get
			{
				return this._Transaccions;
			}
			set
			{
				this._Transaccions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Tarjeta", Storage="_Usuario", ThisKey="IdUsuario", OtherKey="Id", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Tarjetas.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Tarjetas.Add(this);
						this._IdUsuario = value.Id;
					}
					else
					{
						this._IdUsuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Transaccions(Transaccion entity)
		{
			this.SendPropertyChanging();
			entity.Tarjeta = this;
		}
		
		private void detach_Transaccions(Transaccion entity)
		{
			this.SendPropertyChanging();
			entity.Tarjeta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private string _Apellido;
		
		private string _NumeroDocumento;
		
		private int _IdUsuarioRegistro;
		
		private System.DateTime _FechaRegistro;
		
		private System.Nullable<int> _IdUsuarioModifico;
		
		private System.Nullable<System.DateTime> _FechaModifico;
		
		private bool _Eliminado;
		
		private EntitySet<Tarjeta> _Tarjetas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    partial void OnNumeroDocumentoChanging(string value);
    partial void OnNumeroDocumentoChanged();
    partial void OnIdUsuarioRegistroChanging(int value);
    partial void OnIdUsuarioRegistroChanged();
    partial void OnFechaRegistroChanging(System.DateTime value);
    partial void OnFechaRegistroChanged();
    partial void OnIdUsuarioModificoChanging(System.Nullable<int> value);
    partial void OnIdUsuarioModificoChanged();
    partial void OnFechaModificoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaModificoChanged();
    partial void OnEliminadoChanging(bool value);
    partial void OnEliminadoChanged();
    #endregion
		
		public Usuario()
		{
			this._Tarjetas = new EntitySet<Tarjeta>(new Action<Tarjeta>(this.attach_Tarjetas), new Action<Tarjeta>(this.detach_Tarjetas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellido
		{
			get
			{
				return this._Apellido;
			}
			set
			{
				if ((this._Apellido != value))
				{
					this.OnApellidoChanging(value);
					this.SendPropertyChanging();
					this._Apellido = value;
					this.SendPropertyChanged("Apellido");
					this.OnApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroDocumento", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NumeroDocumento
		{
			get
			{
				return this._NumeroDocumento;
			}
			set
			{
				if ((this._NumeroDocumento != value))
				{
					this.OnNumeroDocumentoChanging(value);
					this.SendPropertyChanging();
					this._NumeroDocumento = value;
					this.SendPropertyChanged("NumeroDocumento");
					this.OnNumeroDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioRegistro", DbType="Int NOT NULL")]
		public int IdUsuarioRegistro
		{
			get
			{
				return this._IdUsuarioRegistro;
			}
			set
			{
				if ((this._IdUsuarioRegistro != value))
				{
					this.OnIdUsuarioRegistroChanging(value);
					this.SendPropertyChanging();
					this._IdUsuarioRegistro = value;
					this.SendPropertyChanged("IdUsuarioRegistro");
					this.OnIdUsuarioRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioModifico", DbType="Int")]
		public System.Nullable<int> IdUsuarioModifico
		{
			get
			{
				return this._IdUsuarioModifico;
			}
			set
			{
				if ((this._IdUsuarioModifico != value))
				{
					this.OnIdUsuarioModificoChanging(value);
					this.SendPropertyChanging();
					this._IdUsuarioModifico = value;
					this.SendPropertyChanged("IdUsuarioModifico");
					this.OnIdUsuarioModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifico", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModifico
		{
			get
			{
				return this._FechaModifico;
			}
			set
			{
				if ((this._FechaModifico != value))
				{
					this.OnFechaModificoChanging(value);
					this.SendPropertyChanging();
					this._FechaModifico = value;
					this.SendPropertyChanged("FechaModifico");
					this.OnFechaModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eliminado", DbType="Bit NOT NULL")]
		public bool Eliminado
		{
			get
			{
				return this._Eliminado;
			}
			set
			{
				if ((this._Eliminado != value))
				{
					this.OnEliminadoChanging(value);
					this.SendPropertyChanging();
					this._Eliminado = value;
					this.SendPropertyChanged("Eliminado");
					this.OnEliminadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Tarjeta", Storage="_Tarjetas", ThisKey="Id", OtherKey="IdUsuario")]
		public EntitySet<Tarjeta> Tarjetas
		{
			get
			{
				return this._Tarjetas;
			}
			set
			{
				this._Tarjetas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tarjetas(Tarjeta entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Tarjetas(Tarjeta entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoTransaccion")]
	public partial class TipoTransaccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nombre;
		
		private int _IdUsuarioRegistro;
		
		private System.DateTime _FechaRegistro;
		
		private System.Nullable<int> _IdUsuarioModifico;
		
		private System.Nullable<System.DateTime> _FechaModifico;
		
		private bool _Eliminado;
		
		private EntitySet<Transaccion> _Transaccions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnIdUsuarioRegistroChanging(int value);
    partial void OnIdUsuarioRegistroChanged();
    partial void OnFechaRegistroChanging(System.DateTime value);
    partial void OnFechaRegistroChanged();
    partial void OnIdUsuarioModificoChanging(System.Nullable<int> value);
    partial void OnIdUsuarioModificoChanged();
    partial void OnFechaModificoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaModificoChanged();
    partial void OnEliminadoChanging(bool value);
    partial void OnEliminadoChanged();
    #endregion
		
		public TipoTransaccion()
		{
			this._Transaccions = new EntitySet<Transaccion>(new Action<Transaccion>(this.attach_Transaccions), new Action<Transaccion>(this.detach_Transaccions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioRegistro", DbType="Int NOT NULL")]
		public int IdUsuarioRegistro
		{
			get
			{
				return this._IdUsuarioRegistro;
			}
			set
			{
				if ((this._IdUsuarioRegistro != value))
				{
					this.OnIdUsuarioRegistroChanging(value);
					this.SendPropertyChanging();
					this._IdUsuarioRegistro = value;
					this.SendPropertyChanged("IdUsuarioRegistro");
					this.OnIdUsuarioRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioModifico", DbType="Int")]
		public System.Nullable<int> IdUsuarioModifico
		{
			get
			{
				return this._IdUsuarioModifico;
			}
			set
			{
				if ((this._IdUsuarioModifico != value))
				{
					this.OnIdUsuarioModificoChanging(value);
					this.SendPropertyChanging();
					this._IdUsuarioModifico = value;
					this.SendPropertyChanged("IdUsuarioModifico");
					this.OnIdUsuarioModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifico", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModifico
		{
			get
			{
				return this._FechaModifico;
			}
			set
			{
				if ((this._FechaModifico != value))
				{
					this.OnFechaModificoChanging(value);
					this.SendPropertyChanging();
					this._FechaModifico = value;
					this.SendPropertyChanged("FechaModifico");
					this.OnFechaModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eliminado", DbType="Bit NOT NULL")]
		public bool Eliminado
		{
			get
			{
				return this._Eliminado;
			}
			set
			{
				if ((this._Eliminado != value))
				{
					this.OnEliminadoChanging(value);
					this.SendPropertyChanging();
					this._Eliminado = value;
					this.SendPropertyChanged("Eliminado");
					this.OnEliminadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoTransaccion_Transaccion", Storage="_Transaccions", ThisKey="Id", OtherKey="IdTipoTransaccion")]
		public EntitySet<Transaccion> Transaccions
		{
			get
			{
				return this._Transaccions;
			}
			set
			{
				this._Transaccions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Transaccions(Transaccion entity)
		{
			this.SendPropertyChanging();
			entity.TipoTransaccion = this;
		}
		
		private void detach_Transaccions(Transaccion entity)
		{
			this.SendPropertyChanging();
			entity.TipoTransaccion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transaccion")]
	public partial class Transaccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdTipoTransaccion;
		
		private System.DateTime _Fecha;
		
		private decimal _MontoUSD;
		
		private decimal _MontoPEN;
		
		private int _IdTarjeta;
		
		private int _IdUsuarioRegistro;
		
		private System.DateTime _FechaRegistro;
		
		private System.Nullable<int> _IdUsuarioModifico;
		
		private System.Nullable<System.DateTime> _FechaModifico;
		
		private bool _Eliminado;
		
		private EntityRef<Tarjeta> _Tarjeta;
		
		private EntityRef<TipoTransaccion> _TipoTransaccion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdTipoTransaccionChanging(int value);
    partial void OnIdTipoTransaccionChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnMontoUSDChanging(decimal value);
    partial void OnMontoUSDChanged();
    partial void OnMontoPENChanging(decimal value);
    partial void OnMontoPENChanged();
    partial void OnIdTarjetaChanging(int value);
    partial void OnIdTarjetaChanged();
    partial void OnIdUsuarioRegistroChanging(int value);
    partial void OnIdUsuarioRegistroChanged();
    partial void OnFechaRegistroChanging(System.DateTime value);
    partial void OnFechaRegistroChanged();
    partial void OnIdUsuarioModificoChanging(System.Nullable<int> value);
    partial void OnIdUsuarioModificoChanged();
    partial void OnFechaModificoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaModificoChanged();
    partial void OnEliminadoChanging(bool value);
    partial void OnEliminadoChanged();
    #endregion
		
		public Transaccion()
		{
			this._Tarjeta = default(EntityRef<Tarjeta>);
			this._TipoTransaccion = default(EntityRef<TipoTransaccion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoTransaccion", DbType="Int NOT NULL")]
		public int IdTipoTransaccion
		{
			get
			{
				return this._IdTipoTransaccion;
			}
			set
			{
				if ((this._IdTipoTransaccion != value))
				{
					if (this._TipoTransaccion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTipoTransaccionChanging(value);
					this.SendPropertyChanging();
					this._IdTipoTransaccion = value;
					this.SendPropertyChanged("IdTipoTransaccion");
					this.OnIdTipoTransaccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoUSD", DbType="Decimal(18,2) NOT NULL")]
		public decimal MontoUSD
		{
			get
			{
				return this._MontoUSD;
			}
			set
			{
				if ((this._MontoUSD != value))
				{
					this.OnMontoUSDChanging(value);
					this.SendPropertyChanging();
					this._MontoUSD = value;
					this.SendPropertyChanged("MontoUSD");
					this.OnMontoUSDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoPEN", DbType="Decimal(18,2) NOT NULL")]
		public decimal MontoPEN
		{
			get
			{
				return this._MontoPEN;
			}
			set
			{
				if ((this._MontoPEN != value))
				{
					this.OnMontoPENChanging(value);
					this.SendPropertyChanging();
					this._MontoPEN = value;
					this.SendPropertyChanged("MontoPEN");
					this.OnMontoPENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTarjeta", DbType="Int NOT NULL")]
		public int IdTarjeta
		{
			get
			{
				return this._IdTarjeta;
			}
			set
			{
				if ((this._IdTarjeta != value))
				{
					if (this._Tarjeta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdTarjetaChanging(value);
					this.SendPropertyChanging();
					this._IdTarjeta = value;
					this.SendPropertyChanged("IdTarjeta");
					this.OnIdTarjetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioRegistro", DbType="Int NOT NULL")]
		public int IdUsuarioRegistro
		{
			get
			{
				return this._IdUsuarioRegistro;
			}
			set
			{
				if ((this._IdUsuarioRegistro != value))
				{
					this.OnIdUsuarioRegistroChanging(value);
					this.SendPropertyChanging();
					this._IdUsuarioRegistro = value;
					this.SendPropertyChanged("IdUsuarioRegistro");
					this.OnIdUsuarioRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioModifico", DbType="Int")]
		public System.Nullable<int> IdUsuarioModifico
		{
			get
			{
				return this._IdUsuarioModifico;
			}
			set
			{
				if ((this._IdUsuarioModifico != value))
				{
					this.OnIdUsuarioModificoChanging(value);
					this.SendPropertyChanging();
					this._IdUsuarioModifico = value;
					this.SendPropertyChanged("IdUsuarioModifico");
					this.OnIdUsuarioModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifico", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModifico
		{
			get
			{
				return this._FechaModifico;
			}
			set
			{
				if ((this._FechaModifico != value))
				{
					this.OnFechaModificoChanging(value);
					this.SendPropertyChanging();
					this._FechaModifico = value;
					this.SendPropertyChanged("FechaModifico");
					this.OnFechaModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eliminado", DbType="Bit NOT NULL")]
		public bool Eliminado
		{
			get
			{
				return this._Eliminado;
			}
			set
			{
				if ((this._Eliminado != value))
				{
					this.OnEliminadoChanging(value);
					this.SendPropertyChanging();
					this._Eliminado = value;
					this.SendPropertyChanged("Eliminado");
					this.OnEliminadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tarjeta_Transaccion", Storage="_Tarjeta", ThisKey="IdTarjeta", OtherKey="Id", IsForeignKey=true)]
		public Tarjeta Tarjeta
		{
			get
			{
				return this._Tarjeta.Entity;
			}
			set
			{
				Tarjeta previousValue = this._Tarjeta.Entity;
				if (((previousValue != value) 
							|| (this._Tarjeta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tarjeta.Entity = null;
						previousValue.Transaccions.Remove(this);
					}
					this._Tarjeta.Entity = value;
					if ((value != null))
					{
						value.Transaccions.Add(this);
						this._IdTarjeta = value.Id;
					}
					else
					{
						this._IdTarjeta = default(int);
					}
					this.SendPropertyChanged("Tarjeta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoTransaccion_Transaccion", Storage="_TipoTransaccion", ThisKey="IdTipoTransaccion", OtherKey="Id", IsForeignKey=true)]
		public TipoTransaccion TipoTransaccion
		{
			get
			{
				return this._TipoTransaccion.Entity;
			}
			set
			{
				TipoTransaccion previousValue = this._TipoTransaccion.Entity;
				if (((previousValue != value) 
							|| (this._TipoTransaccion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoTransaccion.Entity = null;
						previousValue.Transaccions.Remove(this);
					}
					this._TipoTransaccion.Entity = value;
					if ((value != null))
					{
						value.Transaccions.Add(this);
						this._IdTipoTransaccion = value.Id;
					}
					else
					{
						this._IdTipoTransaccion = default(int);
					}
					this.SendPropertyChanged("TipoTransaccion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
